_merge = "deep"

baseURL = "https://beta.ecoindex.fr/"

title = "EcoIndex.fr"

defaultContentLanguage = "fr"

disableKinds = ["section", "taxonomy", "term"]

# Do not output RSS for home (default output for home is HTML + RSS)
[outputs]
	home = ["HTML"]
