_merge = "deep"

defaultContentLanguage = "fr"

disableKinds = ["section", "taxonomy", "term"]
title = "EcoIndex.fr"

# Do not output RSS for home (default output for home is HTML + RSS)
[outputs]
	home = ["HTML"]
