baseURL = "/"
title = "Ecoindex"

[permalinks]
  error = "/:filename/"

[languages]

  [languages.en]
  languageCode = "en-us"
  contentDir = "content/en"
  languageName = "English"
  weight = 1.0

  [languages.fr]
  languageCode = "fr"
  contentDir = "content/fr"
  languageName = "Français"
  weight = 2.0

  [[languages.fr.menu.footer]]
    identifier = "joinUs"
    title = "Nous rejoindre"
    url = "/joinus"
    weight = 1

  [[languages.fr.menu.footer]]
    identifier = "github"
    title = "Github"
    url = "https://github.com/cnumr/Ecoindex"
    weight = 2
    [languages.fr.menu.footer.params]
      newtab = true

  [[languages.fr.menu.footer]]
    identifier = "confidentialite"
    title = "Politique de confidentialité"
    url = "/confidentialite"
    weight = 3


# Configure the Markdown renderer.
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets like shortcodes in Markdown content.
      #Wowchemy utilise du JS pour vérifier que le html ne contient pas de code malveillant. Est-ce qu'on veux reprendre ce code pour ecoindex ?
