baseURL = "/"
title = "Ecoindex"

[permalinks]
  error = "/:filename/"

[languages]

  [languages.en]
  languageCode = "en-us"
  contentDir = "content/en"
  languageName = "English"
  weight = 1.0

  [languages.fr]
  languageCode = "fr"
  contentDir = "content/fr"
  languageName = "Français"
  weight = 2.0
