baseURL = "/"
title = "Ecoindex"

[permalinks]
  error = "/:filename/"

[languages]

  [languages.en]
  languageCode = "en-us"
  contentDir = "content/en"
  languageName = "English"
  weight = 1.0

  [languages.fr]
  languageCode = "fr"
  contentDir = "content/fr"
  languageName = "Français"
  weight = 2.0


# Configure the Markdown renderer.
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets like shortcodes in Markdown content.
      #Wowchemy utilise du JS pour vérifier que le html ne contient pas de code malveillant. Est-ce qu'on veux reprendre ce code pour ecoindex ? 
