baseURL = "/"
title = "Ecoindex"

[permalinks]
  pages = "/:filename/"

[languages]

  [languages.en]
  languageName = "English"
  weight = 2.0

  [languages.fr]
  languageName = "Français"
  weight = 1.0
